wget https://s3.amazonaws.com/hello-tc/spacenet3-code/trained_models/model01.pth
wget https://s3.amazonaws.com/hello-tc/spacenet3-code/trained_models/model02.pth
wget https://s3.amazonaws.com/hello-tc/spacenet3-code/trained_models/model03.pth
wget https://s3.amazonaws.com/hello-tc/spacenet3-code/trained_models/model04.pth
wget https://s3.amazonaws.com/hello-tc/spacenet3-code/trained_models/model05.pth
wget https://s3.amazonaws.com/hello-tc/spacenet3-code/trained_models/model06.pth
wget https://s3.amazonaws.com/hello-tc/spacenet3-code/trained_models/model07.pth
wget https://s3.amazonaws.com/hello-tc/spacenet3-code/trained_models/model08.pth
wget https://s3.amazonaws.com/hello-tc/spacenet3-code/trained_models/model09.pth
